# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-imports
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.43.0
    hooks:
      - id: golangci-lint
